### ISSUE TITLE
lua_getupvalue does nothing

### ISSUE THREAD

**Issue by halfling** [malkia/ufo#10]
Hi when I call lua_getupvalue, nothing gets pushed onto the stack. I wrote a test program below showing the problem, the code works with the ordinary lua 5.2.1. I built the latest luajit under linux.

**Comment by malkia** [comment]
Hi halfling,

I think you should post this problem to the luajit mailing list. It's
possible that due to my custom compilation steps I've missed something (I'm
compiling with 5.2 compatibility mode, but it's not full 5.2)

On Mon, Nov 12, 2012 at 1:36 AM, halfling notifications@github.com wrote:

> Hi when I call lua_getupvalue, nothing gets pushed onto the stack. I wrote
> a test program below showing the problem, the code works with the ordinary
> lua 5.2.1. I built the latest luajit under linux.
> 
> "test.cpp" code:
> #include
> #include
> 
> int main() {
> lua_State *L = luaL_newstate();
> luaL_openlibs(L);
> 
> luaL_loadfile(L, "test.lua"); //push thunk with an upvalue containing its
> environment
> std::cout << "stack height = " << lua_gettop(L) << std::endl;
> 
> lua_getupvalue(L,-1,1); //push thunk's environment table
> std::cout << "stack height = " << lua_gettop(L) << std::endl;
> 
> lua_close(L);
> }
> 
> "test.lua":
> print("Hello test")
> 
> "makefile":
> EXE = $(OUT)/test
> OUT = bin
> CC = g++
> 
> CPPFLAGS := pkg-config --cflags luajit
> LDFLAGS := pkg-config --libs luajit -ldl
> 
> .PHONY: all
> all: $(EXE)
> 
> objects := $(patsubst %.cpp,$(OUT)/%.o,$(wildcard *.cpp))
> dependencies := $(objects:.o=.dep)
> -include $(dependencies)
> 
> $(OUT)/%.o: %.cpp
> mkdir -p $(@D https://github.com/D)
> $(CC) $(CPPFLAGS) -c $< -o $@
> $(CC) $(CPPFLAGS) -MM $< | sed -e '1,1 s|[^:]_:|$@:|' > $(@Dhttps://github.com/D
> )/$_.dep
> 
> $(EXE) : $(objects)
> $(CC) $^ $(LDFLAGS) -o $@
> 
> Expected output:
> stack height = 1
> stack height = 2
> 
> Actual output:
> stack height = 1
> stack height = 1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/malkia/ufo/issues/10.

## 

Dimiter "malkia" Stanev,
ICQ: 21875894
malkia@mac.com
malkia@gmail.com

**Comment by halfling** [comment]
Sorry somewhere I must of clicked the wrong link, I thought this was the the main github for the luajit.
