### ISSUE TITLE
Suggestion to build LuaJIT with Lua 5.2 features

### ISSUE THREAD

**Issue by Deco** [malkia/ufo#2]
I've recently begun using this incredibly useful set of tools for various programming endeavours; it's absolutely perfect for building a quick OpenGL demonstration.

The main issue I find with it is the lack of Lua 5.2 features, namely:
- __len metamethod working on tables
- __pairs and __ipairs metamethods

These features are not essential, but they are very convenient.
I also believe that any of the current code will be affected by the changes.

I've managed to compile LuaJIT x64 myself using the WinSDK, but it would be most helpful (for myself and others) if it were built with the flag by default.

**Comment by malkia** [comment]
Hi Deco,

Thanks for the suggestion. I will recompile luajit today it with 5.2
compat (I'm not sure whether it's full 5.2 support, or some of it).

Thanks,
Dimiter "malkia" Stanev.

On Wed, Aug 3, 2011 at 5:37 AM, Deco
reply@reply.github.com
wrote:

> I've recently begun using this incredibly useful set of tools for various programming endeavours; it's absolutely perfect for building a quick OpenGL demonstration.
> 
> The main issue I find with it is the lack of Lua 5.2 features, namely:
> - __len metamethod working on tables
> - __pairs and __ipairs metamethods
> 
> These features are not essential, but they are very convenient.
> I also believe that any of the current code will be affected by the changes.
> 
> I've managed to compile LuaJIT x64 myself using the WinSDK, but it would be most helpful (for myself and others) if it were built with the flag by default.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/malkia/ufo/issues/2

## 

Dimiter "malkia" Stanev,
ICQ: 21875894
malkia@mac.com
malkia@gmail.com

**Comment by malkia** [comment]
I've just submitted this - only for Windows. Thanks for the
suggestion! I should explore more of the 5.2 features.

According to the LuaJIT doc - it's not full 5.2 yet, but many cool
features are there - metatables for lt, gt, etc.

If I have time, I would submit it later for OSX and Linux

On Wed, Aug 3, 2011 at 10:06 AM, malkia malkia@gmail.com wrote:

> Hi Deco,
> 
> Thanks for the suggestion. I will recompile luajit today it with 5.2
> compat (I'm not sure whether it's full 5.2 support, or some of it).
> 
> Please file an issue, if it's not too hard (I've never did it myself
> on github).
> 
> Thanks,
> Dimiter "malkia" Stanev.
> 
> On Wed, Aug 3, 2011 at 5:37 AM, Deco
> reply@reply.github.com
> wrote:
> 
> > I've recently begun using this incredibly useful set of tools for various programming endeavours; it's absolutely perfect for building a quick OpenGL demonstration.
> > 
> > The main issue I find with it is the lack of Lua 5.2 features, namely:
> > - __len metamethod working on tables
> > - __pairs and __ipairs metamethods
> > 
> > These features are not essential, but they are very convenient.
> > I also believe that any of the current code will be affected by the changes.
> > 
> > I've managed to compile LuaJIT x64 myself using the WinSDK, but it would be most helpful (for myself and others) if it were built with the flag by default.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/malkia/ufo/issues/2
> 
> ## 
> 
> Dimiter "malkia" Stanev,
> ICQ: 21875894
> malkia@mac.com
> malkia@gmail.com

## 

Dimiter "malkia" Stanev,
ICQ: 21875894
malkia@mac.com
malkia@gmail.com
